package domain;
import java.util.ArrayList;
import java.util.List;
import java.util.Collections;

/**
 * Base abstract class that represents a user in the social network.
 * Concrete subclasses (e.g. Persoana, Duck) add domain-specific fields.
 */
public abstract class User {
    protected int id;
    protected String username,email,password;
    protected List<User> friends;
    /** Per-user notification inbox populated by subscribed events. */
    private final List<String> notifications = new ArrayList<>();

    /**
     * Create a new User.
     *
     * @param id unique identifier for the user
     * @param name username (display name)
     * @param email user's email address
     * @param password user's password
     */
    public User(int id, String name, String email, String password) {
        this.id = id;
        this.username = name;
        this.email = email;
        this.password = password;
        this.friends=new ArrayList<User>();
    }

    public User(String name, String email, String password) {
        this.id=-1; // uninitialized
        this.username = name;
        this.email = email;
        this.password = password;
        this.friends=new ArrayList<User>();
    }

    /**
     * Add a friend to this user's friend list if not already present and not the same user.
     *
     * @param user the user to add as a friend
     */
    public void addFriend(User user){
        if(!friends.contains(user) && !this.equals(user)){
            friends.add(user);
        }
    }

    /**
     * Get the user's id.
     *
     * @return numeric id
     */
    public int getId() {
        return id;
    }

    /**
     * Assign a persistent id once it is generated by the repository layer.
     * Subsequent calls replace the old value so reloads can keep their ids in sync.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Get the user's username.
     *
     * @return username string
     */
    public String getUsername() {
        return username;
    }

    /**
     * Get the user's email address.
     *
     * @return email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Get the user's password (plain text in this simple example).
     *
     * @return password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Get this user's friends list.
     *
     * @return mutable list of friends
     */
    public List<User> getFriends() {
        return friends;
    }

    /**
     * Remove a friend from this user's friend list.
     *
     * @param user the friend to remove
     */
    public void removeFriend(User user){
        friends.remove(user);
    }

    /**
     * Receive a notification message from an observed event.
     * Events call this when broadcasting updates to subscribers.
     *
     * @param message the message to store (ignored if null)
     */
    public void receiveNotification(String message){
        if(message != null) notifications.add(message);
    }

    /**
     * Read-only view of this user's notifications (in chronological order).
     *
     * @return unmodifiable list of notification messages
     */
    public List<String> getNotifications(){
        return Collections.unmodifiableList(notifications);
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", email='" + email + '\'' +
                ", friends=" + friends.size() +
                '}';
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if(obj==null || getClass()!=obj.getClass()) return false;
        User other=(User) obj;
        return this.id==other.id;
    }
}
